# Generated by Django 5.0.1 on 2024-05-07 14:09

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nome_cognome_import', models.CharField(max_length=150)),
                ('anagrafica_import', models.CharField(max_length=300)),
                ('telefono_principale', models.CharField(max_length=20, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('strada', models.CharField(max_length=100, null=True)),
                ('numero_civico', models.CharField(max_length=50, null=True)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('comune', models.CharField(max_length=50, null=True)),
                ('codicefiscale', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicoCaldaia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
        migrations.CreateModel(
            name='NumeroDiTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data_chiamata', models.DateField()),
                ('data_completamento', models.DateField(null=True)),
                ('data_assegnamento', models.DateField(null=True)),
                ('motivazione', models.CharField(max_length=100)),
                ('note_per_tecnico', models.CharField(max_length=200)),
                ('note_del_tecnico', models.CharField(max_length=200)),
                ('stato', models.CharField(choices=[(1, 'Nuovo'), (2, 'Assegnato'), (3, 'Completato'), (4, 'Bloccato')], default=1, max_length=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.tecnicocaldaia')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
