# Generated by Django 5.0.1 on 2024-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cliente_cognome_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono_principale',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
