# Generated by Django 5.0.1 on 2024-05-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_cliente_telefono_principale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumeroDiTelefono',
            new_name='NumeroDiTelefonoAggiuntivo',
        ),
    ]
