# Generated by Django 5.0.1 on 2024-05-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_numeroditelefono_numeroditelefonoaggiuntivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente'),
        ),
        migrations.AlterField(
            model_name='numeroditelefonoaggiuntivo',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente'),
        ),
    ]
