# Generated by Django 5.0.1 on 2024-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_intervento_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mostra_dati_importati',
            field=models.BooleanField(default=True),
        ),
    ]
