# Generated by Django 5.0.1 on 2024-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cliente_mostra_dati_importati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anagrafica_import',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cognome_import',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
