# Generated by Django 5.0.1 on 2024-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_cliente_anagrafica_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creato_da_importazione',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creato_da_webapp',
            field=models.BooleanField(default=False),
        ),
    ]
