# Generated by Django 5.0.1 on 2024-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_cliente_creato_da_importazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='motivazione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='note_del_tecnico',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='note_per_tecnico',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
