# Generated by Django 5.0.1 on 2024-09-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_intervento_motivazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garanzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_accensione', models.DateField(null=True)),
                ('data_scadenza', models.DateField(null=True)),
                ('matricola', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rapporto', models.DateField(null=True)),
                ('data_scadenza', models.DateField(null=True)),
                ('matricola', models.CharField(max_length=100, null=True)),
                ('tipologia', models.CharField(max_length=100, null=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
            ],
        ),
    ]
